CREATE TABLE IF NOT EXISTS public.cardapio (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    ativo bool NULL,
    dt_alteracao timestamp(6) NULL,
    dt_criacao timestamp(6) NULL,
    nome varchar(50) NOT NULL,
    descricao varchar(1000) NULL,
    preco numeric(19, 2) NOT NULL,
    foto varchar(2000) NULL,
    disponivel bool NOT NULL,
    restaurante_id int4 NOT NULL,
    CONSTRAINT cardapio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cardapio_aud (
    id int4 NOT NULL,
    rev int4 NOT NULL,
    revtype int2 NOT NULL,    
    ativo bool NULL,
    dt_alteracao timestamp(6) NULL,
    dt_criacao timestamp(6) NULL,
    nome varchar(50) NULL,
    descricao varchar(1000) NULL,
    preco numeric(19, 2) NULL,
    foto varchar(2000) NULL,
    disponivel bool NULL,
    restaurante_id int4 NULL,
    CONSTRAINT cardapio_aud_pkey PRIMARY KEY (id, rev)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cardapio_restaurante') THEN
        ALTER TABLE public.cardapio 
        ADD CONSTRAINT fk_cardapio_restaurante 
        FOREIGN KEY (restaurante_id) REFERENCES public.restaurante(id);
    END IF;
END $$;