DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'tipo_usuario'
  ) THEN

  CREATE TABLE public.tipo_usuario (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	descricao varchar(1000) NULL,
	nome varchar(50) NOT NULL,
	CONSTRAINT tipo_usuario_pkey PRIMARY KEY (id));

  CREATE TABLE public.tipo_usuario_aud (
  id INT NOT NULL, 
  rev INT NOT NULL,
  revtype SMALLINT NOT NULL,
  ativo BOOLEAN,            
  dt_alteracao TIMESTAMP(6),
  dt_criacao TIMESTAMP(6),
  descricao VARCHAR(1000),
  nome VARCHAR(50),
  PRIMARY KEY (id, rev));

  END IF;

-- 1. Adicionar a coluna tipo_usuario_id nas tabelas usuario e usuario_aud
ALTER TABLE public.usuario ADD COLUMN tipo_usuario_id INT;
ALTER TABLE public.usuario_aud ADD COLUMN tipo_usuario_id INT;

-- 2. Inserir os tipos de usuário na tabela tipo_usuario (caso não existam)
INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'CLIENTE', 'CLIENTE', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'CLIENTE');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'DONO RESTAURANTE', 'DONO RESTAURANTE', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'DONO RESTAURANTE');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'FORNECEDOR', 'FORNECEDOR', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'FORNECEDOR');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'PRESTADOR SERVICO', 'PRESTADOR SERVICO', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'PRESTADOR SERVICO');

-- 3. Atualizar a tabela usuario mapeando as siglas antigas para os novos IDs

-- Tipo C -> CLIENTE
UPDATE public.usuario u
SET tipo_usuario_id = t.id
FROM public.tipo_usuario t
WHERE u.tipo_usuario = 'C' AND t.nome = 'CLIENTE';

-- Tipo D -> DONO RESTAURANTE
UPDATE public.usuario u
SET tipo_usuario_id = t.id
FROM public.tipo_usuario t
WHERE u.tipo_usuario = 'D' AND t.nome = 'DONO RESTAURANTE';

-- Tipo F -> FORNECEDOR
UPDATE public.usuario u
SET tipo_usuario_id = t.id
FROM public.tipo_usuario t
WHERE u.tipo_usuario = 'F' AND t.nome = 'FORNECEDOR';

-- Tipo P -> PRESTADOR SERVICO
UPDATE public.usuario u
SET tipo_usuario_id = t.id
FROM public.tipo_usuario t
WHERE u.tipo_usuario = 'P' AND t.nome = 'PRESTADOR SERVICO';

-- 4. Criar a Foreign Key (Chave Estrangeira) para garantir integridade
-- Isso garante que o campo tipo_usuario_id sempre aponte para um ID válido
ALTER TABLE public.usuario 
ADD CONSTRAINT fk_usuario_tipo_usuario 
FOREIGN KEY (tipo_usuario_id) REFERENCES public.tipo_usuario(id);

-- Definir a coluna tipo_usuario_id como NOT NULL após a migração
ALTER TABLE public.usuario ALTER COLUMN tipo_usuario_id SET NOT NULL;

-- 5. Remover a coluna antiga 'tipo_usuario' das tabelas
ALTER TABLE public.usuario DROP COLUMN tipo_usuario;
ALTER TABLE public.usuario_aud DROP COLUMN tipo_usuario;

END $$;