-- 1. Criar tabelas tipo_usuario e tipo_usuario_aud se não existirem
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'tipo_usuario'
  ) THEN
    CREATE TABLE public.tipo_usuario (
      id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ativo bool,
      dt_alteracao timestamp(6),
      dt_criacao timestamp(6),
      descricao varchar(1000),
      nome varchar(50) NOT NULL,
      dono bool NOT NULL DEFAULT false
    );

    CREATE TABLE public.tipo_usuario_aud (
      id INT NOT NULL, 
      rev INT NOT NULL,
      revtype SMALLINT NOT NULL,
      ativo BOOLEAN,            
      dt_alteracao TIMESTAMP(6),
      dt_criacao TIMESTAMP(6),
      descricao VARCHAR(1000),
      nome VARCHAR(50),
      dono bool,
      PRIMARY KEY (id, rev)
    );
  END IF;
END $$;

-- 2. Adicionar coluna tipo_usuario_id nas tabelas usuario e usuario_aud
ALTER TABLE public.usuario ADD COLUMN IF NOT EXISTS tipo_usuario_id INT;
ALTER TABLE public.usuario_aud ADD COLUMN IF NOT EXISTS tipo_usuario_id INT;

-- 3. Inserir tipos de usuário (se não existirem)
INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'ADMINISTRADOR', 'ADMINISTRADOR', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'ADMINISTRADOR');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'CLIENTE', 'CLIENTE', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'CLIENTE');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'DONO RESTAURANTE', 'DONO RESTAURANTE', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'DONO RESTAURANTE');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'FORNECEDOR', 'FORNECEDOR', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'FORNECEDOR');

INSERT INTO public.tipo_usuario (nome, descricao, ativo, dt_criacao)
SELECT 'PRESTADOR SERVICO', 'PRESTADOR SERVICO', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_usuario WHERE nome = 'PRESTADOR SERVICO');

-- 4. Atualizar tabela usuario mapeando siglas antigas para IDs
DO $$
BEGIN
  -- Verifica se a coluna tipo_usuario existe na tabela usuario
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'usuario'
      AND column_name = 'tipo_usuario'
  ) THEN

    -- Atualizar tabela usuario mapeando siglas antigas para IDs
    UPDATE public.usuario u
    SET tipo_usuario_id = t.id
    FROM public.tipo_usuario t
    WHERE u.tipo_usuario = 'C' AND t.nome = 'CLIENTE';

    UPDATE public.usuario u
    SET tipo_usuario_id = t.id
    FROM public.tipo_usuario t
    WHERE u.tipo_usuario = 'D' AND t.nome = 'DONO RESTAURANTE';

    UPDATE public.usuario u
    SET tipo_usuario_id = t.id
    FROM public.tipo_usuario t
    WHERE u.tipo_usuario = 'F' AND t.nome = 'FORNECEDOR';

    UPDATE public.usuario u
    SET tipo_usuario_id = t.id
    FROM public.tipo_usuario t
    WHERE u.tipo_usuario = 'P' AND t.nome = 'PRESTADOR SERVICO';

    -- Só depois de atualizar, remover a coluna antiga
    ALTER TABLE public.usuario DROP COLUMN tipo_usuario;
  END IF;

  -- Mesmo raciocínio para usuario_aud
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'usuario_aud'
      AND column_name = 'tipo_usuario'
  ) THEN
    ALTER TABLE public.usuario_aud DROP COLUMN tipo_usuario;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_schema = 'public'
      AND table_name = 'usuario'
      AND constraint_name = 'fk_usuario_tipo_usuario'
  ) THEN
    ALTER TABLE public.usuario
    ADD CONSTRAINT fk_usuario_tipo_usuario
    FOREIGN KEY (tipo_usuario_id) REFERENCES public.tipo_usuario(id);
  END IF;

END $$;


-- 6. Definir coluna como NOT NULL
ALTER TABLE public.usuario ALTER COLUMN tipo_usuario_id SET NOT NULL;

-- 7. Remover coluna antiga
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'usuario'
      AND column_name = 'tipo_usuario'
  ) THEN
    ALTER TABLE public.usuario DROP COLUMN tipo_usuario;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'usuario_aud'
      AND column_name = 'tipo_usuario'
  ) THEN
    ALTER TABLE public.usuario_aud DROP COLUMN tipo_usuario;
  END IF;
END $$;
