ALTER TABLE public.endereco ALTER COLUMN usuario_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS public.tipo_cozinha (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	descricao varchar(1000) NULL,
	nome varchar(50) NOT NULL,
	CONSTRAINT tipo_cozinha_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipo_cozinha_aud (
	id int4 NOT NULL,
	rev int4 NOT NULL,
	revtype int2 NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	descricao varchar(1000) NULL,
	nome varchar(50) NULL,
	CONSTRAINT tipo_cozinha_aud_pkey PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS public.restaurante (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	descricao varchar(1000) NULL,
	nome varchar(50) NOT NULL,
	horario_funcionamento JSON NOT NULL,
	
	endereco_id int4 NOT NULL,
	tipo_cozinha_id int4 NOT NULL,
	usuario_id_dono int4 NOT NULL,
	
	CONSTRAINT restaurante_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.restaurante_aud (
	id int4 NOT NULL,
	rev int4 NOT NULL,
	revtype int2 NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	descricao varchar(1000) NULL,
	nome varchar(50) NULL,
	horario_funcionamento JSON NULL,
	endereco_id int4 NULL,
	tipo_cozinha_id int4 NULL,
	usuario_id_dono int4 NULL,
	CONSTRAINT restaurante_aud_pkey PRIMARY KEY (id, rev)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_restaurante_endereco ON public.restaurante (endereco_id);

DO $$
BEGIN

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_restaurante_endereco') THEN
        ALTER TABLE public.restaurante 
        ADD CONSTRAINT fk_restaurante_endereco FOREIGN KEY (endereco_id) REFERENCES public.endereco(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_restaurante_tipo_cozinha') THEN
        ALTER TABLE public.restaurante 
        ADD CONSTRAINT fk_restaurante_tipo_cozinha FOREIGN KEY (tipo_cozinha_id) REFERENCES public.tipo_cozinha(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_restaurante_usuario_dono') THEN
        ALTER TABLE public.restaurante 
        ADD CONSTRAINT fk_restaurante_usuario_dono FOREIGN KEY (usuario_id_dono) REFERENCES public.usuario(id);
    END IF;

END $$;