services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-myrestaurante}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-restaurante}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# DECLARAÇÃO DOS VOLUMES NOMEADOS
volumes:
  pg_data:
    driver: local