DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'tipo_usuario'
  ) THEN

  CREATE TABLE public.tipo_usuario (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	descricao varchar(1000) NULL,
	nome varchar(50) NOT NULL,
	CONSTRAINT tipo_usuario_pkey PRIMARY KEY (id));

  CREATE TABLE public.tipo_usuario_aud (
  id INT NOT NULL, 
  rev INT NOT NULL,
  revtype SMALLINT NOT NULL,
  ativo BOOLEAN,            
  dt_alteracao TIMESTAMP(6),
  dt_criacao TIMESTAMP(6),
  descricao VARCHAR(1000),
  nome VARCHAR(50),
  PRIMARY KEY (id, rev));

  END IF;
END $$;


DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'usuario'
  ) THEN

  CREATE TABLE public.usuario (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	e_mail varchar(100) NOT NULL,
	nome varchar(50) NOT NULL,
	senha varchar(100) NOT NULL,
	tipo_usuario_id int4 NOT NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id));

  CREATE TABLE public.usuario_aud (
  id INT NOT NULL,      
  rev INT NOT NULL,     
  revtype SMALLINT NOT NULL,
  ativo BOOLEAN,
  dt_alteracao TIMESTAMP(6),
  dt_criacao TIMESTAMP(6),
  e_mail VARCHAR(100),
  nome VARCHAR(50),
  senha VARCHAR(100),
  tipo_usuario_id INT,
  PRIMARY KEY (id, rev));

  CREATE TABLE public.endereco (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	dt_alteracao timestamp(6) NULL,
	dt_criacao timestamp(6) NULL,
	bairro varchar(100) NOT NULL,
	cep varchar(10) NOT NULL,
	complemento varchar(100) NULL,
	logradouro varchar(200) NOT NULL,
	municipio varchar(100) NOT NULL,
	numero varchar(5) NULL,
	ponto_referencia varchar(100) NULL,
	principal bool NOT NULL,
	uf varchar(2) NOT NULL,
	usuario_id int4 NOT NULL,
	CONSTRAINT endereco_pkey PRIMARY KEY (id));

  CREATE TABLE public.endereco_aud (
  id INT NOT NULL,
  rev INT NOT NULL,
  revtype SMALLINT NOT NULL,
  ativo BOOLEAN,
  dt_alteracao TIMESTAMP(6),
  dt_criacao TIMESTAMP(6),
  bairro VARCHAR(100),
  cep VARCHAR(10),
  complemento VARCHAR(100),
  logradouro VARCHAR(200),
  municipio VARCHAR(100),
  numero VARCHAR(5),
  ponto_referencia VARCHAR(100),
  principal BOOLEAN,
  uf VARCHAR(2),
  usuario_id INT,
  PRIMARY KEY (id, rev));

  END IF;
END $$;